name: Add marketing blog content
description: >
  For adding marketing-approved content to the DevBlog.
labels: ["content","developer blog"]
body:
  - type: markdown
    attributes:
      value: |
        Let's get some content up!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: your preferred email and/or dbt Slack handle
    validations:
      required: true

  - type: checkboxes
    id: from-discussion
    attributes:
      label: This issue is being made to create a marketing-approved piece.
      description: >
        This content will typically fall under glossary pages, community recap events, and devblog content for campaigns. Please reach out to John Blust if there's any confusion here.
      options:
        - label: I am directly creating this issue for a marketing-approved piece.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link to the marketing artifact/source material you are referencing.
      description: Please link to the artifact (content brief/event recap) you are using to guide your work.
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Link to the initial outline we will develop through this Issue.
      description: Please link to the initial outline in FigJam, Notion, or Google Docs
    validations:
      required: true