name: Add Issue to Project
on:
  issues

jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        name: Get project data
        id: get_project_info
        with:
          query: |
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }
          org: 'dbt-labs'
          number: 14
          header: 'GraphQL-Features: projects_next_graphql'

        env:
          GITHUB_TOKEN: ${{secrets.ProjectsNext}}

      - run: 
          echo 'Project info:' ${{ steps.get_project_info.outputs.data }} 
